/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as SelectRoleRouteImport } from './routes/select-role'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppComplianceRouteImport } from './routes/app.compliance'
import { Route as AppOverviewRouteImport } from './routes/app.overview'
import { Route as AppRfiRouteImport } from './routes/app.rfi'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectRoleRoute = SelectRoleRouteImport.update({
  id: '/select-role',
  path: '/select-role',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppComplianceRoute = AppComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppRfiRoute = AppRfiRouteImport.update({
  id: '/rfi',
  path: '/rfi',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/select-role': typeof SelectRoleRoute
  '/signin': typeof SigninRoute
  '/app/admin': typeof AppAdminRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/overview': typeof AppOverviewRoute
  '/app/rfi': typeof AppRfiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/select-role': typeof SelectRoleRoute
  '/signin': typeof SigninRoute
  '/app/admin': typeof AppAdminRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/overview': typeof AppOverviewRoute
  '/app/rfi': typeof AppRfiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/select-role': typeof SelectRoleRoute
  '/signin': typeof SigninRoute
  '/app/admin': typeof AppAdminRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/overview': typeof AppOverviewRoute
  '/app/rfi': typeof AppRfiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/select-role'
    | '/signin'
    | '/app/admin'
    | '/app/compliance'
    | '/app/overview'
    | '/app/rfi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/select-role'
    | '/signin'
    | '/app/admin'
    | '/app/compliance'
    | '/app/overview'
    | '/app/rfi'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/select-role'
    | '/signin'
    | '/app/admin'
    | '/app/compliance'
    | '/app/overview'
    | '/app/rfi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SelectRoleRoute: typeof SelectRoleRoute
  SigninRoute: typeof SigninRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-role': {
      id: '/select-role'
      path: '/select-role'
      fullPath: '/select-role'
      preLoaderRoute: typeof SelectRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compliance': {
      id: '/app/compliance'
      path: '/compliance'
      fullPath: '/app/compliance'
      preLoaderRoute: typeof AppComplianceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/overview': {
      id: '/app/overview'
      path: '/overview'
      fullPath: '/app/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rfi': {
      id: '/app/rfi'
      path: '/rfi'
      fullPath: '/app/rfi'
      preLoaderRoute: typeof AppRfiRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppComplianceRoute: typeof AppComplianceRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppRfiRoute: typeof AppRfiRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppComplianceRoute: AppComplianceRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppRfiRoute: AppRfiRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SelectRoleRoute: SelectRoleRoute,
  SigninRoute: SigninRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
